import streamlit as st
st.set_page_config(page_title="Nyumba AI", page_icon="🏠", layout="centered")
st.markdown("# 🏠 Nyumba AI")
st.markdown("**Kenya Housing and Real Estate Intelligence**")
st.info("🚧 **Inaendelea kuundwa** — Hii ni toleo la awali. Vipengele vya kwanza vitakuja hivi karibuni.")
st.markdown("### Vipengele vinavyokuja:")
    st.caption("- Thibitisha hati ya ardhi")
    st.caption("- Bei za nyumba za kukodi")
    st.caption("- Haki za mpangaji")
    st.caption("- Mikopo ya nyumba")
    st.caption("- Tahadhari za ulaghai wa ardhi")
st.markdown("---")
st.caption("⭐ Star repo hii ili kufuatilia maendeleo | gabrielmahia.ai")
